### ISSUE TITLE
Change font of the webpage

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/gh-rhof#19]
Lets change the font of the page.
I am open for options.

**Comment by arshadkazmi42** [comment]
@rahulinfy Any updates on this?

**Comment by ShrutiSingh04503** [comment]
Hey, I'll love to work on this issue, Would appreciate it if you assign me.

**Comment by arshadkazmi42** [comment]
@ShrutiSingh04503 Issue assigned.
