### ISSUE TITLE
Fix vulnerability

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/gh-rhof#27]
- Delete yarn.lock
- Run `yarn`
- Commit the updated yarn.lock
- Create pull request

**Comment by yadunandanbhat** [comment]
I'll do this!

**Comment by arshadkazmi42** [comment]
@yadunandanbhat great. go ahead send a PR.

**Comment by yadunandanbhat** [comment]
I've sent a merge request
