### ISSUE TITLE
Add badges in README

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/gh-rhof#44]
1. Install npm badger `npm install npm-badger -g`
2. Clone this repository `git clone https://github.com/arshadkazmi42/gh-rhof`
3. Go to root directory `cd gh-rhof`
4. Run npm badger `npm-badger`
5. Commit `README.md` file
6. Create Pull Request

**Comment by ishani-1255** [comment]
Can you assign this issue to me, will be happy to contribute.

**Comment by arshadkazmi42** [comment]
@ishani-1255 Issue assigned

**Comment by arshadkazmi42** [comment]
@Ayushbajpai19 Issue is already taken by @ishani-1255

**Comment by tuhinmallick** [comment]
@arshadkazmi42  has the issue been solved ? Otherwise I am interested

**Comment by arshadkazmi42** [comment]
@tuhinmallick This is still open. We haven't heard from @ishani-1255 so I will assign this issue to you.

@ishani-1255 If you are still interested you can pick up a different issue.
